version: '3.5'
services:
  main_server:
    build: 
      context: ./cinema-server
    restart: always
    volumes:
      - ./cinema-server/public:/images/uploads
    ports:
      - 8080:54000
    networks:
      - db-net
    depends_on:
      - db
      
  crawle_server:
    build: 
      context: ./crawle-server
    restart: always
    ports:
      - 8070:53000
    networks:
      - db-net
    depends_on:
      - db

  db:
    image: mysql:8.0.20
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - db-net
    ports:
      - 8086:3306
volumes:
  movie-poster:
networks:
  db-net:
      
